export enum HighlightId {
  Generator1 = 'generator-1',
  Generator2 = 'generator-2',
  Generator3 = 'generator-3',
  Generator4 = 'generator-4',
  Generator5 = 'generator-5',
  Generator6 = 'generator-6',
  Generator7 = 'generator-7',
  Generator8 = 'generator-8',
  Generator9 = 'generator-9',
  Generator10 = 'generator-10',
  Steps = 'steps',
  Ticks = 'ticks',
  BuyAmountButton = 'buyAmountButton',
  UpgradesTab = 'upgradesTab',
  PrestigeTab = 'prestigeTab',
  ManagerUpgrades = 'managerUpgrades',
  ManagerUpgrade1 = 'managerUpgrade1',
}