export const cashRegister = require('./cash-register.mp3')
export const menuSelectionClick = require('./menu-selection-click.wav')
export const switchOn = require('./switch-on.mp3')
export const winning = require('./winning.wav')
export const coinWinning = require('./coin-winning.wav')
export const click = require('./click.mp3')